#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/ros-ikuai-monitor-panel}"
SRC_DIR="${SRC_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
VENV_DIR="${APP_DIR}/.venv"
ENV_FILE="/etc/default/routeros-panel"
SERVICE_FILE="/etc/systemd/system/routeros-panel.service"
IP_SERVICE_FILE="/etc/systemd/system/ros-panel-ip.service"

ROS_PANEL_BIND="${ROS_PANEL_BIND:-0.0.0.0}"
ROS_PANEL_PORT="${ROS_PANEL_PORT:-80}"
ROS_PANEL_TARGET_IP="${ROS_PANEL_TARGET_IP:-192.168.3.5}"
ROS_PANEL_IFACE="${ROS_PANEL_IFACE:-ens192}"
ROS_PANEL_BIND_CIDR="${ROS_PANEL_BIND_CIDR:-24}"
ROS_PANEL_IP_HEAL_SECONDS="${ROS_PANEL_IP_HEAL_SECONDS:-3}"
ROS_MONITOR_ROUTER_HOST="${ROS_MONITOR_ROUTER_HOST:-192.168.3.1}"
ROS_MONITOR_ROUTER_USER="${ROS_MONITOR_ROUTER_USER:-admin}"
ROS_MONITOR_ROUTER_PASSWORD="${ROS_MONITOR_ROUTER_PASSWORD:-<REDACTED_ROUTER_PASSWORD>}"
ROS_MONITOR_POLL_SECONDS="${ROS_MONITOR_POLL_SECONDS:-1}"
ROS_MONITOR_STATIC_POLL_SECONDS="${ROS_MONITOR_STATIC_POLL_SECONDS:-300}"
ROS_MONITOR_STATIC_REST_WORKERS="${ROS_MONITOR_STATIC_REST_WORKERS:-1}"
ROS_MONITOR_SLOW_REST_POLL_SECONDS="${ROS_MONITOR_SLOW_REST_POLL_SECONDS:-60}"
ROS_MONITOR_SLOW_REST_WORKERS="${ROS_MONITOR_SLOW_REST_WORKERS:-2}"
ROS_MONITOR_CONNECTION_DETAIL_POLL_SECONDS="${ROS_MONITOR_CONNECTION_DETAIL_POLL_SECONDS:-30}"
ROS_MONITOR_CONNECTION_PROTOCOL_POLL_SECONDS="${ROS_MONITOR_CONNECTION_PROTOCOL_POLL_SECONDS:-30}"

sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python3-venv python3-pip rsync curl

sudo mkdir -p "${APP_DIR}"
sudo rsync -a --delete \
  --exclude '.venv' \
  --exclude '__pycache__' \
  --exclude '*.pyc' \
  --exclude '*.log' \
  --exclude '_sample*.json' \
  "${SRC_DIR}/" "${APP_DIR}/"

sudo python3 -m venv "${VENV_DIR}"
sudo PIP_DISABLE_PIP_VERSION_CHECK=1 "${VENV_DIR}/bin/pip" install --progress-bar off --upgrade pip
sudo PIP_DISABLE_PIP_VERSION_CHECK=1 "${VENV_DIR}/bin/pip" install --progress-bar off -r "${APP_DIR}/requirements.txt"

sudo install -m 0644 "${APP_DIR}/routeros-panel.service" "${SERVICE_FILE}"
sudo install -m 0644 "${APP_DIR}/ros-panel-ip.service" "${IP_SERVICE_FILE}"

sudo tee "${ENV_FILE}" >/dev/null <<EOF
PYTHONUNBUFFERED=1
ROS_PANEL_BIND=${ROS_PANEL_BIND}
ROS_PANEL_PORT=${ROS_PANEL_PORT}
ROS_PANEL_TARGET_IP=${ROS_PANEL_TARGET_IP}
ROS_PANEL_IFACE=${ROS_PANEL_IFACE}
ROS_PANEL_BIND_CIDR=${ROS_PANEL_BIND_CIDR}
ROS_PANEL_IP_HEAL_SECONDS=${ROS_PANEL_IP_HEAL_SECONDS}
ROS_MONITOR_ROUTER_HOST=${ROS_MONITOR_ROUTER_HOST}
ROS_MONITOR_ROUTER_USER=${ROS_MONITOR_ROUTER_USER}
ROS_MONITOR_ROUTER_PASSWORD=${ROS_MONITOR_ROUTER_PASSWORD}
ROS_MONITOR_POLL_SECONDS=${ROS_MONITOR_POLL_SECONDS}
ROS_MONITOR_STATIC_POLL_SECONDS=${ROS_MONITOR_STATIC_POLL_SECONDS}
ROS_MONITOR_STATIC_REST_WORKERS=${ROS_MONITOR_STATIC_REST_WORKERS}
ROS_MONITOR_SLOW_REST_POLL_SECONDS=${ROS_MONITOR_SLOW_REST_POLL_SECONDS}
ROS_MONITOR_SLOW_REST_WORKERS=${ROS_MONITOR_SLOW_REST_WORKERS}
ROS_MONITOR_CONNECTION_DETAIL_POLL_SECONDS=${ROS_MONITOR_CONNECTION_DETAIL_POLL_SECONDS}
ROS_MONITOR_CONNECTION_PROTOCOL_POLL_SECONDS=${ROS_MONITOR_CONNECTION_PROTOCOL_POLL_SECONDS}
EOF

sudo systemctl daemon-reload
sudo systemctl enable ros-panel-ip.service routeros-panel.service
sudo systemctl restart ros-panel-ip.service
sudo systemctl restart routeros-panel.service

sleep 5
sudo systemctl --no-pager --full status ros-panel-ip.service routeros-panel.service || true
curl -fsS "http://${ROS_PANEL_TARGET_IP}/api/health"

